spring :
  jpa :
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibername:
        format_sql: true

    # 테이블 생성 후 data.sql 실행
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true